### ISSUE TITLE
一点疑惑

### ISSUE THREAD

**Issue by jcdong98** [polossk/ExpressionRunner#1]
博士您好，我注意到您自己实现了异常处理机制，但是这导致了有许多块代码都是类似于如下的形式：
`
if ( ... )
{
	error.something( ... );
	return false;
}
`
我想这样会不会显得过于繁琐，若采用 try - throw - catch 这个语言级别的异常处理机制会不会使得程序实现变得简单一些。抑或是处于某种方面的考虑，博士认为此处用这种方式不太妥当，进而采用了较为繁琐的写法。

——某辣鸡学弟前来仰望博士...

**Comment by polossk** [comment]
try-throw-catch当时的确采用了这个架构，不过那时候太年轻，直接throw会导致调用exit(1)退出程序，后来就索性弃用了单独去写了自己的异常类。。。

反膜董先森
