### ISSUE TITLE
一些可能的BUG及问题反馈

### ISSUE THREAD

**Issue by jcdong98** [polossk/ExpressionRunner#2]
博士您好，弱在折腾了这个很有趣的 ExpressionRunner 一段之间后，很抱歉再次打扰您。

首先发现一个BUG（抑或是 feature ?），便是幂运算的结合性问题。幂运算不满足结合律，并且在数学上以及几乎全部已知的软件中，幂运算都是右结合的。然而由于您的实现应该是采用中缀表达式转逆波兰表达式求值，却很遗憾您的实现默认了所有的二元运算都是满足左结合律的，进而会导致一些预期之外的结果。解决的方法弱想也不难，只需在遇到运算优先级相同的右结合二元运算符时，不需要急着出栈即可。因此，在对每一个运算符考虑优先级的时候，也需要考虑其结合性。

以下的内容是可能会被“乱玩”玩坏的地方（应该不能算做 BUG）。

似乎`1e5`, `1.2e-4` 这样的“浮点数”并未支持，但是 C/C++ 的 IO 都是支持直接读入此类浮点数的。

可以进行一些非常“荒诞”的操作，比如
`rm PI`
`inf := 0`
`nan := 233`
没有支持将 builtin 的符号 protect 起来
（此处扯一下 Mathematica 的应对... MMA 中当然也可以 `Unprotect[Pi]`, `Unprotect[Infinity]` 然后将其 `Remove` 掉之类操作，但是这样之后再进行比如 `ArcCos[-1]` 的时候便不能得到预想的结果了。）
然而这里比如 `inf := 0` 之后， 运算 `10 ^ 309` 得到的答案是 `10 ^ 309 = inf`，如果等式右侧的inf认为就是一个符号而非具体数值的话，那么弱认为就不应该允许修改 inf 的值，不过这点小瑕疵也无伤大雅...

像 1 = 2 这类对常量的赋值虽然会有 ERROR，但是会多输出一句 `1 = 2 = nan`，弱认为这是不必要的...

直接输出表达式 `--`，虽然会有 ERROR，但是程序会陷入死循环。

最后，如果博士忙于科研工作，或是对多年前的项目早已不感兴趣，弱可以等有时间的时候来尝试维护一下，不过可能要等弱学会如何使用 git ...

最后的最后继续仰望一波博士，orz...

**Comment by polossk** [comment]
一个一个说：
变量可修改是个feature，当时主要是懒。然后得出结果那点，这里输出的就是正常的inf或nan，是不影响的。

**Comment by polossk** [comment]
浮点数输入是bug，因为没处理这种类型的输入

**Comment by polossk** [comment]
这项目我觉得可以弃了，不如直接去写一个脚本语言虚拟机实在一些233
